name: storage_benchmark

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  moor: # use the latest version
  sqlite3_flutter_libs: # Also use the latest version.
  path_provider:
  path:
  random_string:
  hive:
  sqflite:
  shared_preferences:
  fl_chart:
#  moor_ffi:
  sembast:
  get_storage:
  chips_choice:

dev_dependencies:
  flutter_rename_app:
  moor_generator: # use the latest version
  build_runner:

flutter_rename_app:
  application_name: storage_benchmark
  dart_package_name: storage_benchmark
  application_id: com.android.storage_benchmark
  bundle_id: com.ios.storage_benchmark
  android_package_name: com.storage_benchmark.app

flutter:
  uses-material-design: true